### ISSUE TITLE
RTSP does not response

### ISSUE THREAD

**Issue by thematrixdev** [mnakada/atomcam_tools#3] opened 2022-03-16 08:05 UTC
RTSP sometimes does not response. Reboot may not help.

![image](https://user-images.githubusercontent.com/19472561/158544222-d5a9ebfa-522d-4b57-affd-e7d616337ee2.png)

atom.log
https://pastebin.com/iwF5xHLr

rtspserver.log
```
log level:500
```

Thanks.

**Comment by mnakada** [comment] 2022-03-18 13:36
In my environment, I don't seem to have the same problem with the same settings.

Below are some things to check if RTSP is not working properly.
- Stability of WiFi connection
　Are other wireless devices interfering with the communication and delaying it?
　Turning on RTSP over HTTP may improve connectivity.

- SD-Card performance
　Since it is used for linux swap, the SD-Card should be as fast as possible.
　However, it must be FAT-formatted with 32GB or less to boot.

- Checking the load of iCamera_app
　Login with ssh and use the top command to check the load when RTSP is interrupted.
　It may be caused by something that is running at the same time and has a high load.

**Comment by thematrixdev** [comment] 2022-03-18 15:29
Thanks for your reply.

- Wifi connection is good.

- Maybe the SD-card I am using is slow. I am using the blue one 16GB. No write-speed is specified.
https://personal.kioxia.com/en-apac/micro-sd/exceria.html

- iCamera_app is under 40% load. And `Load average: 2.39 2.26 2.30`.
Maybe I will try to get the information next time RTSP is dead.

By the way, I have found something strange.
Now I have set RTSP-over-HTTP.
```
$ top | grep v4l2rtspserver

606     1 root     S    91860123.6   0  3.4 /usr/bin/v4l2rtspserver -p 8080 -C 1 -a S16_LE -l 0 /dev/video1,hw:Loopback,0
```
rtsp://192.168.50.61:8080/unicast does stream video.
However, rtsp://192.168.50.61:8554/unicast is also streaming video.
Is it normal?

**Comment by thematrixdev** [comment] 2022-03-18 16:01
I have just updated to 1.2.13 and hence rebooted.
After reboot, there is no response neither from 8080 or 8554.
I see the rtsp process is still there.
![image](https://user-images.githubusercontent.com/19472561/159038607-5c132ebe-b4b1-4cea-9e1a-62d9da27ff34.png)

**Comment by mnakada** [comment] 2022-03-19 02:39
> Maybe the SD-card I am using is slow. I am using the blue one 16GB. No write-speed is specified.

SD-Card is probably not that slow.

> iCamera_app is under 40% load. And Load average: 2.39 2.26 2.30.
Maybe I will try to get the information next time RTSP is dead.

iCamera_app load of about 40% is normal.
Check it when you have a problem.

> However, rtsp://192.168.50.61:8554/unicast is also streaming video.
Is it normal?

RTSP over HTTP is normal to output both port 8554/udp and port 8080/tcp.
If the connection is broken due to AtomCam's internal load, it has no effect.
It works if the UDP packet is dropped somewhere in the communication path.

> I have just updated to 1.2.13 and hence rebooted.
After reboot, there is no response neither from 8080 or 8554.
I see the rtsp process is still there.

Sorry. Last night I published a few minutes of failed images.
If your web UI version notation is Ver. 1.2.12, you have written that image.
If you UPDATE again, it will be fixed correctly.

**Comment by thematrixdev** [comment] 2022-03-19 02:45
> Sorry. Last night I published a few minutes of failed images. If your web UI version notation is Ver. 1.2.12, you have written that image. If you UPDATE again, it will be fixed correctly.

I noticed you have switched the release file. I have click "update" on the UI afterwards.
The RTSP connection did not start after I have kept the camera running overnight.
Finally I switched off RTSP-over-HTTP, clicked "設定", RTSP is back.
I suspect toggling the setting may help restarting the RTSP service.

**Comment by mnakada** [comment] 2022-03-19 08:02
> The RTSP connection did not start after I have kept the camera running overnight.

I will check if the RTSP output continues for a long time.

> Finally I switched off RTSP-over-HTTP, clicked "設定", RTSP is back.
I suspect toggling the setting may help restarting the RTSP service.

Switching RTSP-over-HTTP will restart v4l2rtspserver.
I may need a program to monitor that it is stopped.

**Comment by 13310** [comment] 2022-03-20 03:55
I am in the same situation. Indeed, the v4l2rtspserver process is STOPPING once every 2-3 days when "RTSP over HTTP" is enabled.
I am using my zabbix to monitor tcp/8080 for TCP polling and reboot atomcam when tcp/8080 becomes unresponsive.

**Comment by thematrixdev** [comment] 2022-03-20 06:12
> I am in the same situation. Indeed, the v4l2rtspserver process is STOPPING once every 2-3 days when "RTSP over HTTP" is enabled. I am using my zabbix to monitor tcp/8080 for TCP polling and reboot atomcam when tcp/8080 becomes unresponsive.

I had been using 8554. I have found RTSP no response and then tried switching to 8080.
I think RTSP just stop responding periodically regardless of protocol.

By the way, it seems there is no RTSP-stop after updating to 1.2.13.

**Comment by mnakada** [comment] 2022-03-20 08:20
RTSPServer has been running continuously in my environment for about 24 hours.
No problems occurred.

In Ver. 1.2.14, I added a watchdog that monitors several statuses along with RTSPServer.

I have not seen the problem occur, so I do not know if the countermeasure is effective.
However, when I KILL the process, it restarts a minute later.

**Comment by thematrixdev** [comment] 2022-03-20 09:15
Updated. Thanks.

**Comment by 13310** [comment] 2022-03-20 23:57
@mnakada 
Thanks, I also updated.

@thematrixdev 
> Do you reboot your camera manually? I wonder if we can reboot it with API.

I have checked the sequence of events when the reboot button is pressed from the configuration screen. I then reproduced it with the curl command.
As follows.
`curl -X POST -H "Content-Type: application/json" -d '{"exec":"reboot"}' http://***.***.***.***/cgi-bin/cmd.cgi?port=undefined`

**Comment by mnakada** [comment] 2022-03-21 07:50
Close this issue.
If you encounter any problems, please re-open the issue.

FYI
The cmd.cgi command is executed in one of the following two files

port=null:
configs/overlay_rootfs/scripts/webcmd.sh

port=socket:
libcallback/command.c

**Closed by mnakada** 2022-03-21 07:50 UTC
